FROM fedora:latest as builder

RUN yum install -y httpd
COPY ./website1.html /var/www/html/website1.html

EXPOSE 80

ENTRYPOINT ["httpd", "-DFOREGROUND"]


FROM builder as website1
COPY ./website2.html /var/www/html/website2.html


FROM website1 as website2
COPY ./website2.html /var/www/html/website2.html
